// Default config values mirroring crates/xode-core/src/config.rs (used by the mock and "Reset" buttons).
import type { Config } from "./types";

export const DEFAULT_COMPACT_PROMPT =
  "CONTEXT LIMIT REACHED. Stop working and write a handoff for yourself. The context will be cleared and you will continue from this handoff only. Do not call tools.\nReply with exactly:\n<path>\n- up to {path_lines} one-line bullets: what you did since the last handoff (files changed, key findings, commands that worked). Terse, no filler.\n</path>\n<state>\nuser: <what the user wants right now, one line in their terms; if they moved on to a new task, only the newest one>\ngoal: <one line>\ndone: <one line>\nnow: <what you were doing at the cut>\nnext: <next 1-3 concrete steps>\nnotes: <facts needed to continue: paths, symbols, decisions, gotchas>\n</state>\nMax {state_words} words inside <state>.";

export const DEFAULT_SEED_TEMPLATE =
  "[Context was compacted. Continue the task from here without redoing finished work. Do not re-read files listed in the working set unless you must edit a part you have not seen.]\n\n{request}\n\n## Project path (.xode/PATH.md)\n{path}\n\n## State\n{state}\n\n{goal}\n\n{working_set}";

export const TOOL_NAMES = ["read", "write", "edit", "glob", "grep", "shell", "code", "web_search", "web_fetch", "browser"];

export function defaultConfig(): Config {
  return {
    gateways: [],
    selected: { gateway: "", model: "", mode: "normal" },
    generation: {
      temperature: null,
      top_p: null,
      top_k: null,
      min_p: null,
      repeat_penalty: null,
      presence_penalty: null,
      frequency_penalty: null,
      max_tokens: 16384,
      seed: null,
      reasoning_effort: "",
      reasoning_budget: { low: 2048, medium: 8192, high: 24576 },
      stop: [],
      extra_body: "",
      keep_thinking: false,
      parallel_tool_calls: true,
      request_timeout_s: 900,
    },
    compaction: {
      enabled: true,
      context_limit: 0,
      fallback_context: 98304,
      threshold_tokens: 0,
      threshold_ratio: 0.82,
      hard_ratio: 0.93,
      reserve_tokens: 2048,
      path_file: ".xode/PATH.md",
      path_max_lines: 60,
      path_entry_max_lines: 6,
      state_max_words: 180,
      keep_recent_messages: 2,
      include_working_set: true,
      working_set_max_files: 16,
      include_repo_map: true,
      keep_original_request: true,
      fold_old_entries: true,
      prompt: DEFAULT_COMPACT_PROMPT,
      seed_template: DEFAULT_SEED_TEMPLATE,
    },
    token_saving: {
      rtk_enabled: true,
      rtk_strip_ansi: true,
      rtk_collapse_progress: true,
      rtk_dedup_lines: true,
      rtk_command_filters: true,
      max_tool_output_tokens: 4000,
      head_lines: 60,
      tail_lines: 80,
      save_full_output: true,
      read_dedup: true,
      read_max_lines: 400,
      repo_map_tokens: 1200,
      attach_inline_max_tokens: 6000,
      drop_old_thinking: true,
      stub_old_tool_results_after: 0,
    },
    permissions: {
      full_access: true,
      tools: Object.fromEntries(TOOL_NAMES.map((t) => [t, "allow"])) as Config["permissions"]["tools"],
      shell_rules: [
        { pattern: "rm -rf /*", perm: "ask" },
        { pattern: "format *", perm: "ask" },
        { pattern: "Remove-Item * -Recurse*C:\\", perm: "ask" },
        { pattern: "git push*", perm: "ask" },
      ],
      path_rules: [],
      allow_outside_project: "allow",
      network: "allow",
      browser: "allow",
    },
    browser: {
      kind: "edge",
      executable: "",
      debug_port: 9222,
      mode: "attach",
      user_data_dir: "",
      profile: "Default",
      headless: false,
      extra_args: [],
      snapshot_max_tokens: 3000,
    },
    mcp: [],
    tools: {
      enabled: {},
      shell: "auto",
      shell_timeout_s: 300,
      search_order: ["duckduckgo", "searxng", "brave", "tavily", "browser"],
      searxng_url: "",
      brave_key: "",
      tavily_key: "",
      search_results: 6,
      fetch_max_tokens: 4000,
      index_enabled: true,
      index_watch: true,
      index_max_file_kb: 512,
      grep_max_results: 80,
      glob_max_results: 200,
      edit_fuzzy: true,
      goal_judge: true,
    },
    theme: { preset: "fluent-blue", blur: true, tokens: {}, font_size: 14, mono_font: "" },
    notifications: { permission: true, finished: true, errors: true, sound: true, only_unfocused: true },
    knowledge: {
      enabled: true,
      embedder: "builtin",
      builtin_model: "multilingual-e5-small",
      gateway: "",
      gateway_model: "",
      chunk_tokens: 400,
      k: 8,
      outline_tokens: 600,
      read_max_tokens: 2000,
      ai_write_global: true,
      ai_write_project: true,
    },
    system_prompt_extra: "",
  };
}
